#############################################################################
# Makefile for building: nettopo
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? 11? 17 14:33:27 2011
# Project:  nettopo.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile nettopo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		netnode.cpp \
		nodeframe.cpp \
		nodelink.cpp \
		suspensiondialog.cpp moc_netnode.cpp \
		moc_nodeframe.cpp \
		moc_suspensiondialog.cpp
OBJECTS       = main.o \
		netnode.o \
		nodeframe.o \
		nodelink.o \
		suspensiondialog.o \
		moc_netnode.o \
		moc_nodeframe.o \
		moc_suspensiondialog.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		nettopo.pro
QMAKE_TARGET  = nettopo
DESTDIR       = 
TARGET        = nettopo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nettopo.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile nettopo.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile nettopo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nettopo1.0.0 || $(MKDIR) .tmp/nettopo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nettopo1.0.0/ && $(COPY_FILE) --parents netnode.h nodeframe.h nodelink.h suspensiondialog.h tree.h .tmp/nettopo1.0.0/ && $(COPY_FILE) --parents main.cpp netnode.cpp nodeframe.cpp nodelink.cpp suspensiondialog.cpp .tmp/nettopo1.0.0/ && (cd `dirname .tmp/nettopo1.0.0` && $(TAR) nettopo1.0.0.tar nettopo1.0.0 && $(COMPRESS) nettopo1.0.0.tar) && $(MOVE) `dirname .tmp/nettopo1.0.0`/nettopo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nettopo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_netnode.cpp moc_nodeframe.cpp moc_suspensiondialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_netnode.cpp moc_nodeframe.cpp moc_suspensiondialog.cpp
moc_netnode.cpp: suspensiondialog.h \
		netnode.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) netnode.h -o moc_netnode.cpp

moc_nodeframe.cpp: netnode.h \
		suspensiondialog.h \
		nodeframe.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) nodeframe.h -o moc_nodeframe.cpp

moc_suspensiondialog.cpp: suspensiondialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) suspensiondialog.h -o moc_suspensiondialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp nodeframe.h \
		netnode.h \
		suspensiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

netnode.o: netnode.cpp netnode.h \
		suspensiondialog.h \
		nodeframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netnode.o netnode.cpp

nodeframe.o: nodeframe.cpp nodelink.h \
		netnode.h \
		suspensiondialog.h \
		nodeframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodeframe.o nodeframe.cpp

nodelink.o: nodelink.cpp nodelink.h \
		netnode.h \
		suspensiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodelink.o nodelink.cpp

suspensiondialog.o: suspensiondialog.cpp suspensiondialog.h \
		netnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o suspensiondialog.o suspensiondialog.cpp

moc_netnode.o: moc_netnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_netnode.o moc_netnode.cpp

moc_nodeframe.o: moc_nodeframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nodeframe.o moc_nodeframe.cpp

moc_suspensiondialog.o: moc_suspensiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_suspensiondialog.o moc_suspensiondialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

